string = input("Enter the string: ")
sub_string = input("Enter the substring want to replace: ")
replace_string = input("Enter the replace string: ")
new_string = string.replace(sub_string,replace_string)
print(new_string)